import { Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Portfolio Vakar Florenta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable}  antialiased`}
      >
        <div className="absolute inset-0 -z-10 h-[3200px]  w-full 
      [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">
        {children}
        </div>
      </body>
    </html>
  );
}
